version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_IMPORT: /opt/keycloak/data/import/myrealm.json
    ports:
      - "8080:8080"
    volumes:
      - ./myrealm.json:/opt/keycloak/data/import/myrealm.json
      - ./master-realm.json:/opt/keycloak/data/import/master-realm.json
    command: start-dev

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: